#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
import sys
if __name__ == "__main__":
   sys.path.insert(0, "../")
from pagebotnano_025 import openFont

font = openFont("../masters/Upgrade_CJK_Try-Regular82.ufo") 

def g(f, groupName, group):
   f.groups[groupName] = group

g(font, "TC1.I", ('I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis', 'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Iota', 'Itilde'))
g(font, "TC1.comma", ('colon', 'ellipsis', 'period'))
g(font, "TC1.eight_dnom", ('eight.dnom', 'eight.numr', 'eight.sinf', 'eight.sups'))
g(font, "TC1.exclam", ('exclam', 'exclamdown'))
g(font, "TC1.five_dnom", ('five.dnom', 'five.numr', 'five.sinf', 'five.sups', 'fiveeighths'))
g(font, "TC1.four_dnom", ('four.dnom', 'four.numr', 'four.sinf', 'four.sups'))
g(font, "TC1.i", ('dotlessi', 'i', 'iacute', 'ibreve', 'icircumflex', 'idieresis', 'igrave', 'imacron', 'iogonek', 'itilde'))
g(font, "TC1.nine_dnom", ('nine.dnom', 'nine.numr', 'nine.sinf', 'nine.sups'))
g(font, "TC1.one_dnom", ('one.dnom', 'one.numr', 'one.sinf', 'one.sups', 'oneeighth', 'onefifth', 'onehalf', 'onequarter', 'onesuperior', 'onethird'))
g(font, "TC1.seven_dnom", ('seven.dnom', 'seven.numr', 'seven.sinf', 'seven.sups', 'seveneighths'))
g(font, "TC1.six_dnom", ('six.dnom', 'six.numr', 'six.sinf', 'six.sups'))
g(font, "TC1.three_dnom", ('three.dnom', 'three.numr', 'three.sinf', 'three.sups', 'threeeighths', 'threequarters', 'threesuperior'))
g(font, "TC1.two_dnom", ('two.dnom', 'two.numr', 'two.sinf', 'two.sups', 'twosuperior', 'twothirds'))
g(font, "TC1.zero_dnom", ('percent', 'perthousand', 'zero.dnom', 'zero.numr', 'zero.sinf', 'zero.sups'))
g(font, "TC2.I", ('I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis', 'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Iota', 'Itilde'))
g(font, "TC2.comma", ('colon', 'comma', 'ellipsis', 'period', 'quotedblbase', 'quotedblright', 'quoteright', 'quotesinglbase', 'semicolon'))
g(font, "TC2.eight_dnom", ('eight.dnom', 'eight.numr', 'eight.sinf', 'eight.sups', 'fiveeighths', 'oneeighth', 'seveneighths', 'threeeighths'))
g(font, "TC2.exclam", ('exclam', 'exclamdown'))
g(font, "TC2.five_dnom", ('five.dnom', 'five.numr', 'five.sinf', 'five.sups'))
g(font, "TC2.four_dnom", ('four.dnom', 'four.numr', 'four.sinf', 'four.sups', 'onequarter', 'threequarters'))
g(font, "TC2.guillemotleft", ('guillemotleft', 'guilsinglleft'))
g(font, "TC2.guillemotright", ('guillemotright', 'guilsinglright'))
g(font, "TC2.i", ('dotlessi', 'i', 'iacute', 'ibreve', 'icircumflex', 'idieresis', 'igrave', 'imacron', 'iogonek', 'itilde'))
g(font, "TC2.j", ('dotlessj', 'j', 'jcircumflex'))
g(font, "TC2.nine_dnom", ('nine.dnom', 'nine.numr', 'nine.sinf', 'nine.sups'))
g(font, "TC2.one_dnom", ('one.dnom', 'one.numr', 'one.sinf', 'one.sups', 'onesuperior'))
g(font, "TC2.seven_dnom", ('seven.dnom', 'seven.numr', 'seven.sinf', 'seven.sups'))
g(font, "TC2.six_dnom", ('six.dnom', 'six.numr', 'six.sinf', 'six.sups'))
g(font, "TC2.three_dnom", ('oneeighth', 'onethird', 'three.dnom', 'three.numr', 'three.sinf', 'three.sups'))
g(font, "TC2.two_dnom", ('onehalf', 'two.dnom', 'two.numr', 'two.sinf', 'two.sups'))
g(font, "TC2.zero", ('zero', 'zero.salt_slash'))
g(font, "TC2.zero_dnom", ('percent', 'perthousand', 'zero.dnom', 'zero.numr', 'zero.sinf', 'zero.sups'))
g(font, "eight", ('TC1.eight_numr', 'TC2.eight_numr'))
g(font, "five", ('TC1.five_numr', 'TC2.five_numr'))
g(font, "four", ('TC1.four_numr', 'TC2.four_numr'))
g(font, "nine", ('TC1.nine_numr', 'TC2.nine_numr'))
g(font, "one", ('TC1.one_numr', 'TC2.one_numr'))
g(font, "public.kern1.A", ('A', 'Aacute', 'Abreve', 'Acircumflex', 'Adieresis', 'Agrave', 'Alpha', 'Alphatonos', 'Amacron', 'Aogonek', 'Aring', 'Aringacute', 'Atilde', 'Delta', 'Lambda'))
g(font, "public.kern1.Acyrillic", ('Acyrillic',))
g(font, "public.kern1.B", ('B', 'Beta'))
g(font, "public.kern1.Becyrillic", ('Becyrillic',))
g(font, "public.kern1.C", ('C', 'Cacute', 'Ccaron', 'Ccedilla', 'Ccircumflex', 'Cdotaccent'))
g(font, "public.kern1.Decyrillic", ('Chedescendercyrillic', 'Decyrillic', 'Shchacyrillic', 'Tsecyrillic'))
g(font, "public.kern1.Djecyrillic", ('Djecyrillic', 'Tshecyrillic'))
g(font, "public.kern1.Dzecyrillic", ('Dzecyrillic',))
g(font, "public.kern1.E", ('AE', 'AEacute', 'E', 'Eacute', 'Ebreve', 'Ecaron', 'Ecircumflex', 'Edieresis', 'Edotaccent', 'Egrave', 'Emacron', 'Eogonek', 'Epsilon', 'OE'))
g(font, "public.kern1.Ecyrillic", ('Ecyrillic',))
g(font, "public.kern1.Efcyrillic", ('Efcyrillic',))
g(font, "public.kern1.Ercyrillic", ('Ercyrillic',))
g(font, "public.kern1.F", ('F',))
g(font, "public.kern1.G", ('G', 'Gbreve', 'Gcaron', 'Gcircumflex', 'Gcommaaccent', 'Gdotaccent'))
g(font, "public.kern1.Gecyrillic", ('Gecyrillic', 'Gheupturncyrillic', 'Gjecyrillic', 'Tecyrillic'))
g(font, "public.kern1.H", ('Eng', 'Eta', 'Etatonos', 'H', 'Hcircumflex', 'M', 'Mu', 'N', 'Nacute', 'Ncaron', 'Ncommaaccent', 'Ntilde', 'Nu', 'Pi'))
g(font, "public.kern1.I", ('I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis', 'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Iota', 'Iotadieresis', 'Iotatonos', 'Itilde'))
g(font, "public.kern1.Iecyrillic", ('IEgravecyrillic', 'Iecyrillic', 'Iocyrillic'))
g(font, "public.kern1.Iicyrillic", ('Dzhecyrillic', 'Emcyrillic', 'Encyrillic', 'IAcyrillic', 'Icyrillic', 'Igravecyrillic', 'Iicyrillic', 'Iishortcyrillic', 'Pecyrillic', 'Shacyrillic', 'Yericyrillic'))
g(font, "public.kern1.J", ('IJ', 'J'))
g(font, "public.kern1.Jcircumflex", ('Jcircumflex',))
g(font, "public.kern1.Jecyrillic", ('Jecyrillic',))
g(font, "public.kern1.K", ('Chi', 'K', 'Kappa', 'Kcommaaccent', 'X'))
g(font, "public.kern1.L", ('L',))
g(font, "public.kern1.Lacute", ('Lacute',))
g(font, "public.kern1.Lcaron", ('Lcaron',))
g(font, "public.kern1.Ldot", ('Ldot',))
g(font, "public.kern1.Lslash", ('Lslash',))
g(font, "public.kern1.O", ('D', 'Dcaron', 'Dcroat', 'Eth', 'O', 'Oacute', 'Obreve', 'Ocircumflex', 'Odieresis', 'Ograve', 'Ohungarumlaut', 'Omacron', 'Omicron', 'Omicrontonos', 'Oslash', 'Oslashacute', 'Otilde', 'Q', 'Theta'))
g(font, "public.kern1.Ocyrillic", ('Ereversedcyrillic', 'IUcyrillic', 'Ocyrillic'))
g(font, "public.kern1.Omega", ('Omega', 'Omegatonos'))
g(font, "public.kern1.P", ('P', 'Rho'))
g(font, "public.kern1.Phi", ('Phi',))
g(font, "public.kern1.Psi", ('Psi',))
g(font, "public.kern1.R", ('R', 'Racute', 'Rcaron', 'Rcommaaccent'))
g(font, "public.kern1.S", ('S', 'Sacute', 'Scaron', 'Scedilla', 'Scircumflex', 'Scommaaccent', 'dollar'))
g(font, "public.kern1.Sigma", ('Sigma',))
g(font, "public.kern1.Softsigncyrillic", ('Hardsigncyrillic', 'Ljecyrillic', 'Njecyrillic', 'Softsigncyrillic'))
g(font, "public.kern1.T", ('Gamma', 'T', 'Tau', 'Tbar', 'Tcaron', 'Tcedilla', 'Tcommaaccent'))
g(font, "public.kern1.Thorn", ('Thorn',))
g(font, "public.kern1.U", ('U', 'Uacute', 'Ubreve', 'Ucircumflex', 'Udieresis', 'Ugrave', 'Uhungarumlaut', 'Umacron', 'Uogonek', 'Uring', 'Utilde'))
g(font, "public.kern1.Ucyrillic", ('Ucyrillic', 'Ushortcyrillic'))
g(font, "public.kern1.Ustraightstrokecyrillic", ('Ustraightstrokecyrillic',))
g(font, "public.kern1.V", ('V',))
g(font, "public.kern1.Vecyrillic", ('Vecyrillic',))
g(font, "public.kern1.W", ('W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wgrave'))
g(font, "public.kern1.Y", ('Upsilon', 'Upsilondieresis', 'Upsilontonos', 'Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ygrave'))
g(font, "public.kern1.Yicyrillic", ('Yicyrillic',))
g(font, "public.kern1.Z", ('Z', 'Zacute', 'Zcaron', 'Zdotaccent', 'Zeta'))
g(font, "public.kern1.Zecyrillic", ('Zecyrillic',))
g(font, "public.kern1.Zhecyrillic", ('Kacyrillic', 'Khacyrillic', 'Kjecyrillic', 'Zhecyrillic'))
g(font, "public.kern1.Zhedescendercyrillic", ('Hadescendercyrillic', 'Kadescendercyrillic', 'Zhedescendercyrillic'))
g(font, "public.kern1.a", ('a', 'aacute', 'abreve', 'acircumflex', 'adieresis', 'agrave', 'amacron', 'aogonek', 'aring', 'aringacute', 'atilde'))
g(font, "public.kern1.acyrillic", ('acyrillic',))
g(font, "public.kern1.alpha", ('alpha', 'alphatonos'))
g(font, "public.kern1.ampersand", ('ampersand',))
g(font, "public.kern1.approxequal", ('approxequal',))
g(font, "public.kern1.asciicircum", ('asciicircum',))
g(font, "public.kern1.asciitilde", ('asciitilde',))
g(font, "public.kern1.asterisk", ('asterisk',))
g(font, "public.kern1.at", ('at',))
g(font, "public.kern1.backslash", ('backslash',))
g(font, "public.kern1.bar", ('bar', 'brokenbar'))
g(font, "public.kern1.becyrillic", ('becyrillic',))
g(font, "public.kern1.braceleft", ('braceleft',))
g(font, "public.kern1.braceright", ('braceright',))
g(font, "public.kern1.bracketleft", ('bracketleft',))
g(font, "public.kern1.bracketright", ('bracketright',))
g(font, "public.kern1.bullet", ('bullet',))
g(font, "public.kern1.c", ('c', 'cacute', 'ccaron', 'ccedilla', 'ccircumflex', 'cdotaccent', 'cent'))
g(font, "public.kern1.checkmark", ('checkmark',))
g(font, "public.kern1.circumflex", ('circumflex',))
g(font, "public.kern1.colon", ('colon',))
g(font, "public.kern1.comma", ('comma', 'quotedblbase', 'quotesinglbase'))
g(font, "public.kern1.currency", ('currency',))
g(font, "public.kern1.dagger", ('dagger',))
g(font, "public.kern1.daggerdbl", ('daggerdbl',))
g(font, "public.kern1.dcroat", ('dcroat',))
g(font, "public.kern1.decyrillic", ('decyrillic', 'shchacyrillic', 'tsecyrillic'))
g(font, "public.kern1.degree", ('degree',))
g(font, "public.kern1.divide", ('divide',))
g(font, "public.kern1.djecyrillic", ('djecyrillic', 'tshecyrillic'))
g(font, "public.kern1.dotaccent", ('dotaccent',))
g(font, "public.kern1.dotlessi", ('dotlessi',))
g(font, "public.kern1.dzecyrillic", ('dzecyrillic',))
g(font, "public.kern1.e", ('ae', 'aeacute', 'e', 'eacute', 'ebreve', 'ecaron', 'ecircumflex', 'edieresis', 'edotaccent', 'egrave', 'emacron', 'eogonek', 'oe'))
g(font, "public.kern1.ecyrillic", ('ecyrillic',))
g(font, "public.kern1.eight", ('eight',))
g(font, "public.kern1.eight_numr", ('eight.numr',))
g(font, "public.kern1.eight_sinf", ('eight.sinf',))
g(font, "public.kern1.eight_sups", ('eight.sups',))
g(font, "public.kern1.epsilon", ('epsilon', 'epsilontonos'))
g(font, "public.kern1.equal", ('equal',))
g(font, "public.kern1.escyrillic", ('escyrillic',))
g(font, "public.kern1.eta", ('epsietalon', 'etatonos'))
g(font, "public.kern1.eth", ('eth',))
g(font, "public.kern1.f", ('f', 'f_f'))
g(font, "public.kern1.five", ('five',))
g(font, "public.kern1.five_numr", ('five.numr',))
g(font, "public.kern1.five_sinf", ('five.sinf',))
g(font, "public.kern1.five_sups", ('five.sups',))
g(font, "public.kern1.florin", ('florin',))
g(font, "public.kern1.four", ('four',))
g(font, "public.kern1.four_numr", ('four.numr',))
g(font, "public.kern1.four_sinf", ('four.sinf',))
g(font, "public.kern1.four_sups", ('four.sups',))
g(font, "public.kern1.fraction", ('fraction',))
g(font, "public.kern1.g", ('g', 'gbreve', 'gcaron', 'gcircumflex', 'gcommaaccent', 'gdotaccent', 'q'))
g(font, "public.kern1.gecyrillic", ('gecyrillic', 'gheupturncyrillic', 'gjecyrillic', 'tecyrillic'))
g(font, "public.kern1.germandbls", ('germandbls',))
g(font, "public.kern1.greater", ('greater', 'greaterequal'))
g(font, "public.kern1.guillemotleft", ('guillemotleft', 'guilsinglleft'))
g(font, "public.kern1.guillemotright", ('guillemotright', 'guilsinglright'))
g(font, "public.kern1.horizontal", ('horizontalbar',))
g(font, "public.kern1.hyphen", ('emdash', 'endash', 'hyphen'))
g(font, "public.kern1.i", ('i', 'f_i', 'f_f_i'))
g(font, "public.kern1.iacute", ('iacute',))
g(font, "public.kern1.ibreve", ('ibreve',))
g(font, "public.kern1.icircumflex", ('icircumflex',))
g(font, "public.kern1.icyrillic", ('icyrillic', 'jecyrillic'))
g(font, "public.kern1.idieresis", ('idieresis',))
g(font, "public.kern1.iecyrillic", ('iecyrillic', 'iegravecyrillic', 'iocyrillic'))
g(font, "public.kern1.igrave", ('igrave',))
g(font, "public.kern1.iicyrillic", ('checyrillic', 'dzhecyrillic', 'elcyrillic', 'emcyrillic', 'encyrillic', 'iacyrillic', 'iicyrillic', 'iishortcyrillic', 'pecyrillic', 'shacyrillic', 'yericyrillic'))
g(font, "public.kern1.imacron", ('imacron',))
g(font, "public.kern1.infinity", ('infinity',))
g(font, "public.kern1.integral", ('integral',))
g(font, "public.kern1.iogonek", ('iogonek',))
g(font, "public.kern1.itilde", ('itilde',))
g(font, "public.kern1.j", ('dotlessj', 'f_j', 'ij', 'ij.salt_serif', 'j'))
g(font, "public.kern1.jcircumflex", ('jcircumflex',))
g(font, "public.kern1.k", ('k', 'kcommaaccent'))
g(font, "public.kern1.l", ('d', 'f_f_l', 'f_l', 'l'))
g(font, "public.kern1.lacute", ('lacute',))
g(font, "public.kern1.lcaron", ('dcaron', 'lcaron'))
g(font, "public.kern1.ldot", ('ldot',))
g(font, "public.kern1.less", ('less', 'lessequal'))
g(font, "public.kern1.logicalnot", ('logicalnot',))
g(font, "public.kern1.lozenge", ('lozenge',))
g(font, "public.kern1.lslash", ('lslash',))
g(font, "public.kern1.macron", ('macron',))
g(font, "public.kern1.minus", ('minus',))
g(font, "public.kern1.multiply", ('multiply',))
g(font, "public.kern1.n", ('eng', 'h', 'hbar', 'hcircumflex', 'm', 'n', 'nacute', 'napostrophe', 'ncaron', 'ncommaaccent', 'ntilde'))
g(font, "public.kern1.nine", ('nine',))
g(font, "public.kern1.nine_numr", ('nine.numr',))
g(font, "public.kern1.nine_sinf", ('nine.sinf',))
g(font, "public.kern1.nine_sups", ('nine.sups',))
g(font, "public.kern1.notequal", ('notequal',))
g(font, "public.kern1.numbersign", ('numbersign',))
g(font, "public.kern1.o", ('b', 'o', 'oacute', 'obreve', 'ocircumflex', 'odieresis', 'ograve', 'ohungarumlaut', 'omacron', 'omicron', 'omicrontonos', 'oslash', 'oslashacute', 'otilde', 'p', 'phi', 'rho', 'thorn'))
g(font, "public.kern1.ocyrillic", ('efcyrillic', 'ercyrillic', 'ereversedcyrillic', 'iucyrillic', 'ocyrillic'))
g(font, "public.kern1.one", ('one',))
g(font, "public.kern1.one_numr", ('one.numr',))
g(font, "public.kern1.one_sinf", ('one.sinf',))
g(font, "public.kern1.one_sups", ('one.sups',))
g(font, "public.kern1.onehalf", ('onehalf',))
g(font, "public.kern1.onequarter", ('onequarter',))
g(font, "public.kern1.ord", ('ordfeminine', 'ordmasculine'))
g(font, "public.kern1.paragraph", ('paragraph',))
g(font, "public.kern1.parenleft", ('parenleft',))
g(font, "public.kern1.parenright", ('parenright',))
g(font, "public.kern1.partialdiff", ('partialdiff',))
g(font, "public.kern1.percent", ('percent', 'perthousand'))
g(font, "public.kern1.period", ('ellipsis', 'period'))
g(font, "public.kern1.periodcentered", ('periodcentered',))
g(font, "public.kern1.pi", ('pi',))
g(font, "public.kern1.plus", ('plus', 'plusminus'))
g(font, "public.kern1.product", ('product',))
g(font, "public.kern1.question", ('question',))
g(font, "public.kern1.questiondown", ('questiondown',))
g(font, "public.kern1.quoteleft", ('quotedblleft', 'quoteleft'))
g(font, "public.kern1.quoteright", ('quotedblright', 'quoteright'))
g(font, "public.kern1.quotesingle", ('minute', 'quotedbl', 'quotesingle', 'second'))
g(font, "public.kern1.r", ('r', 'racute', 'rcommaaccent'))
g(font, "public.kern1.radical", ('radical',))
g(font, "public.kern1.registered", ('copyright', 'registered'))
g(font, "public.kern1.s", ('s', 'sacute', 'scaron', 'scedilla', 'scircumflex', 'scommaaccent'))
g(font, "public.kern1.schwa", ('schwa',))
g(font, "public.kern1.section", ('section',))
g(font, "public.kern1.semicolon", ('semicolon',))
g(font, "public.kern1.seven", ('seven',))
g(font, "public.kern1.seven_numr", ('seven.numr',))
g(font, "public.kern1.seven_sinf", ('seven.sinf',))
g(font, "public.kern1.seven_sups", ('seven.sups',))
g(font, "public.kern1.six", ('six',))
g(font, "public.kern1.six_numr", ('six.numr',))
g(font, "public.kern1.six_sinf", ('six.sinf',))
g(font, "public.kern1.six_sups", ('six.sups',))
g(font, "public.kern1.slash", ('slash',))
g(font, "public.kern1.softsigncyrillic", ('hardsigncyrillic', 'ljecyrillic', 'njecyrillic', 'softsigncyrillic'))
g(font, "public.kern1.space", ('space',))
g(font, "public.kern1.sterling", ('sterling',))
g(font, "public.kern1.summation", ('summation',))
g(font, "public.kern1.t", ('t', 'tbar', 'tcedilla', 'tcommaaccent'))
g(font, "public.kern1.tcaron", ('tcaron',))
g(font, "public.kern1.three", ('three',))
g(font, "public.kern1.three_numr", ('three.numr',))
g(font, "public.kern1.three_sinf", ('three.sinf',))
g(font, "public.kern1.three_sups", ('three.sups',))
g(font, "public.kern1.threequarters", ('threequarters',))
g(font, "public.kern1.tilde", ('tilde',))
g(font, "public.kern1.two", ('two',))
g(font, "public.kern1.two_numr", ('two.numr',))
g(font, "public.kern1.two_sinf", ('two.sinf',))
g(font, "public.kern1.two_sups", ('two.sups',))
g(font, "public.kern1.u", ('u', 'uacute', 'ubreve', 'ucircumflex', 'udieresis', 'ugrave', 'umacron', 'uogonek', 'uring', 'utilde'))
g(font, "public.kern1.ucyrillic", ('ucyrillic', 'ushortcyrillic'))
g(font, "public.kern1.uhungarumlaut", ('uhungarumlaut',))
g(font, "public.kern1.underscore", ('underscore',))
g(font, "public.kern1.ustraightstrokecyrillic", ('ustraightstrokecyrillic',))
g(font, "public.kern1.v", ('nu', 'v', 'w', 'wacute', 'wcircumflex', 'wdieresis', 'wgrave'))
g(font, "public.kern1.vecyrillic", ('vecyrillic',))
g(font, "public.kern1.x", ('x',))
g(font, "public.kern1.y", ('y', 'yacute', 'ycircumflex', 'ydieresis', 'ygrave'))
g(font, "public.kern1.yen", ('yen',))
g(font, "public.kern1.yicyrillic", ('yicyrillic',))
g(font, "public.kern1.z", ('z', 'zacute', 'zcaron', 'zdotaccent'))
g(font, "public.kern1.zecyrillic", ('zecyrillic',))
g(font, "public.kern1.zero", ('zero',))
g(font, "public.kern1.zero_numr", ('zero.numr',))
g(font, "public.kern1.zero_salt_slash", ('zero.salt_slash',))
g(font, "public.kern1.zero_sinf", ('zero.sinf',))
g(font, "public.kern1.zero_sups", ('zero.sups',))
g(font, "public.kern1.zhecyrillic", ('kacyrillic', 'khacyrillic', 'kjecyrillic', 'zhecyrillic'))
g(font, "public.kern1.zhedescendercyrillic", ('hadescendercyrillic', 'kadescendercyrillic', 'zhedescendercyrillic'))
g(font, "public.kern2.A", ('A', 'Aacute', 'Abreve', 'Acircumflex', 'Adieresis', 'Agrave', 'Alpha', 'Amacron', 'Aogonek', 'Aring', 'Aringacute', 'Atilde', 'Delta', 'Lambda'))
g(font, "public.kern2.AE", ('AE', 'AEacute'))
g(font, "public.kern2.Acyrillic", ('Acyrillic',))
g(font, "public.kern2.Checyrillic", ('Checyrillic', 'Chedescendercyrillic'))
g(font, "public.kern2.Dcroat", ('Dcroat', 'Eth'))
g(font, "public.kern2.Decyrillic", ('Decyrillic',))
g(font, "public.kern2.Djecyrillic", ('Djecyrillic', 'Hardsigncyrillic', 'Tecyrillic', 'Tshecyrillic'))
g(font, "public.kern2.Dzecyrillic", ('Dzecyrillic',))
g(font, "public.kern2.Ecyrillic", ('Ecyrillic', 'Escyrillic', 'Ocyrillic'))
g(font, "public.kern2.Efcyrillic", ('Efcyrillic',))
g(font, "public.kern2.Ereversedcyrillic", ('Ereversedcyrillic',))
g(font, "public.kern2.Euro", ('Euro',))
g(font, "public.kern2.H", ('B', 'Beta', 'D', 'Dcaron', 'E', 'Eacute', 'Ebreve', 'Ecaron', 'Ecircumflex', 'Edieresis', 'Edotaccent', 'Egrave', 'Emacron', 'Eng', 'Eogonek', 'Epsilon', 'Eta', 'F', 'Gamma', 'H', 'Hcircumflex', 'K', 'Kappa', 'Kcommaaccent', 'L', 'Lcommaaccent', 'Ldot', 'M', 'Mu', 'N', 'Nacute', 'Ncaron', 'Ncommaaccent', 'Ntilde', 'Nu', 'P', 'Pi', 'R', 'Racute', 'Rcaron', 'Rcommaaccent', 'Rho', 'Thorn'))
g(font, "public.kern2.I", ('I', 'IJ', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis', 'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Iota', 'Iotadieresis', 'Itilde'))
g(font, "public.kern2.IAcyrillic", ('IAcyrillic',))
g(font, "public.kern2.Icyrillic", ('Becyrillic', 'Dzhecyrillic', 'Emcyrillic', 'Encyrillic', 'Ercyrillic', 'Gecyrillic', 'Gheupturncyrillic', 'Gjecyrillic', 'IEgravecyrillic', 'IUcyrillic', 'Icyrillic', 'Iecyrillic', 'Igravecyrillic', 'Iicyrillic', 'Iishortcyrillic', 'Iocyrillic', 'Kacyrillic', 'Kadescendercyrillic', 'Kjecyrillic', 'Njecyrillic', 'Pecyrillic', 'Shacyrillic', 'Shchacyrillic', 'Softsigncyrillic', 'Tsecyrillic', 'Vecyrillic', 'Yericyrillic'))
g(font, "public.kern2.J", ('J',))
g(font, "public.kern2.Jcircumflex", ('Jcircumflex',))
g(font, "public.kern2.Jecyrillic", ('Jecyrillic',))
g(font, "public.kern2.Ljecyrillic", ('Elcyrillic', 'Ljecyrillic'))
g(font, "public.kern2.O", ('C', 'Cacute', 'Ccaron', 'Ccedilla', 'Ccircumflex', 'Cdotaccent', 'G', 'Gbreve', 'Gcaron', 'Gcircumflex', 'Gcommaaccent', 'Gdotaccent', 'O', 'OE', 'Oacute', 'Obreve', 'Ocircumflex', 'Odieresis', 'Ograve', 'Ohorn', 'Ohungarumlaut', 'Omacron', 'Omicron', 'Oslash', 'Oslashacute', 'Otilde', 'Q', 'Theta'))
g(font, "public.kern2.Omega", ('Omega',))
g(font, "public.kern2.Phi", ('Phi',))
g(font, "public.kern2.Psi", ('Psi',))
g(font, "public.kern2.S", ('S', 'Sacute', 'Scaron', 'Scedilla', 'Scircumflex', 'Scommaaccent', 'dollar'))
g(font, "public.kern2.Sigma", ('Sigma',))
g(font, "public.kern2.T", ('T', 'Tau', 'Tbar', 'Tcaron', 'Tcedilla', 'Tcommaaccent'))
g(font, "public.kern2.U", ('U', 'Uacute', 'Ubreve', 'Ucircumflex', 'Udieresis', 'Ugrave', 'Uhungarumlaut', 'Umacron', 'Uogonek', 'Uring', 'Utilde'))
g(font, "public.kern2.Ucyrillic", ('Ucyrillic', 'Ushortcyrillic'))
g(font, "public.kern2.Ustraightstrokecyrillic", ('Ustraightstrokecyrillic',))
g(font, "public.kern2.V", ('V',))
g(font, "public.kern2.W", ('W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wgrave'))
g(font, "public.kern2.X", ('Chi', 'X'))
g(font, "public.kern2.Xi", ('Xi',))
g(font, "public.kern2.Y", ('Upsilon', 'Upsilondieresis', 'Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ygrave'))
g(font, "public.kern2.Yicyrillic", ('Yicyrillic',))
g(font, "public.kern2.Z", ('Z', 'Zacute', 'Zcaron', 'Zdotaccent', 'Zeta'))
g(font, "public.kern2.Zecyrillic", ('Zecyrillic',))
g(font, "public.kern2.Zhecyrillic", ('Hadescendercyrillic', 'Khacyrillic', 'Zhecyrillic', 'Zhedescendercyrillic'))
g(font, "public.kern2.a", ('a', 'aacute', 'abreve', 'acircumflex', 'adieresis', 'ae', 'aeacute', 'agrave', 'amacron', 'aogonek', 'aring', 'aringacute', 'atilde'))
g(font, "public.kern2.acyrillic", ('acyrillic',))
g(font, "public.kern2.alpha", ('alpha', 'alphatonos'))
g(font, "public.kern2.ampersand", ('ampersand',))
g(font, "public.kern2.approxequal", ('approxequal',))
g(font, "public.kern2.asciicircum", ('asciicircum',))
g(font, "public.kern2.asciitilde", ('asciitilde',))
g(font, "public.kern2.asterisk", ('asterisk',))
g(font, "public.kern2.at", ('at',))
g(font, "public.kern2.backslash", ('backslash',))
g(font, "public.kern2.bar", ('bar', 'brokenbar'))
g(font, "public.kern2.becyrillic", ('becyrillic',))
g(font, "public.kern2.braceleft", ('braceleft',))
g(font, "public.kern2.braceright", ('braceright',))
g(font, "public.kern2.bracketleft", ('bracketleft',))
g(font, "public.kern2.bracketright", ('bracketright',))
g(font, "public.kern2.bullet", ('bullet',))
g(font, "public.kern2.checkmark", ('checkmark',))
g(font, "public.kern2.checyrillic", ('checyrillic', 'chedescendercyrillic'))
g(font, "public.kern2.circumflex", ('circumflex',))
g(font, "public.kern2.colon", ('colon',))
g(font, "public.kern2.comma", ('comma', 'quotedblbase', 'quotesinglbase'))
g(font, "public.kern2.currency", ('currency',))
g(font, "public.kern2.dagger", ('dagger',))
g(font, "public.kern2.daggerdbl", ('daggerdbl',))
g(font, "public.kern2.decyrillic", ('decyrillic',))
g(font, "public.kern2.degree", ('degree',))
g(font, "public.kern2.divide", ('divide',))
g(font, "public.kern2.djecyrillic", ('djecyrillic', 'tshecyrillic'))
g(font, "public.kern2.dotaccent", ('dotaccent',))
g(font, "public.kern2.dotlessi", ('dotlessi',))
g(font, "public.kern2.dotlessj", ('dotlessj',))
g(font, "public.kern2.dzecyrillic", ('dzecyrillic',))
g(font, "public.kern2.eight_numr", ('eight.numr',))
g(font, "public.kern2.eight_sinf", ('eight.sinf',))
g(font, "public.kern2.eight_sups", ('eight.sups',))
g(font, "public.kern2.elcyrillic", ('elcyrillic', 'ljecyrillic'))
g(font, "public.kern2.epsilon", ('epsilon', 'epsilontonos'))
g(font, "public.kern2.equal", ('equal',))
g(font, "public.kern2.ereversedcyrillic", ('ereversedcyrillic',))
g(font, "public.kern2.eta", ('eta', 'etatonos'))
g(font, "public.kern2.f", ('f', 'f_f', 'f_f_i', 'f_f_l', 'f_i', 'f_l'))
g(font, "public.kern2.five", ('five',))
g(font, "public.kern2.five_numr", ('five.numr',))
g(font, "public.kern2.five_sinf", ('five.sinf',))
g(font, "public.kern2.five_sups", ('five.sups',))
g(font, "public.kern2.florin", ('florin',))
g(font, "public.kern2.four", ('four',))
g(font, "public.kern2.four_numr", ('four.numr',))
g(font, "public.kern2.four_sinf", ('four.sinf',))
g(font, "public.kern2.four_sups", ('four.sups',))
g(font, "public.kern2.fraction", ('fraction',))
g(font, "public.kern2.g", ('g', 'gbreve', 'gcaron', 'gcircumflex', 'gcommaaccent', 'gdotaccent'))
g(font, "public.kern2.germandbls", ('germandbls',))
g(font, "public.kern2.greater", ('greater', 'greaterequal'))
g(font, "public.kern2.guillemotleft", ('guillemotleft', 'guilsinglleft'))
g(font, "public.kern2.guillemotright", ('guillemotright', 'guilsinglright'))
g(font, "public.kern2.h", ('b', 'h', 'k', 'kcommaaccent', 'l', 'lcaron', 'ldot', 'mu', 'thorn'))
g(font, "public.kern2.hbar", ('hbar',))
g(font, "public.kern2.horizontal", ('horizontalbar',))
g(font, "public.kern2.hungarumlaut", ('hungarumlaut',))
g(font, "public.kern2.hungarumlautcmb", ('hungarumlautcmb',))
g(font, "public.kern2.hyphen", ('emdash', 'endash', 'hyphen'))
g(font, "public.kern2.i", ('i',))
g(font, "public.kern2.iacute", ('iacute',))
g(font, "public.kern2.iacyrillic", ('iacyrillic',))
g(font, "public.kern2.ibreve", ('ibreve',))
g(font, "public.kern2.icircumflex", ('icircumflex',))
g(font, "public.kern2.icyrillic", ('icyrillic',))
g(font, "public.kern2.idieresis", ('idieresis',))
g(font, "public.kern2.iecyrillic", ('ecyrillic', 'efcyrillic', 'escyrillic', 'iecyrillic', 'iegravecyrillic', 'iocyrillic', 'ocyrillic'))
g(font, "public.kern2.igrave", ('igrave',))
g(font, "public.kern2.imacron", ('imacron',))
g(font, "public.kern2.infinity", ('infinity',))
g(font, "public.kern2.integral", ('integral',))
g(font, "public.kern2.iogonek", ('iogonek',))
g(font, "public.kern2.itilde", ('itilde',))
g(font, "public.kern2.j", ('j',))
g(font, "public.kern2.jcircumflex", ('jcircumflex',))
g(font, "public.kern2.jecyrillic", ('jecyrillic',))
g(font, "public.kern2.lacute", ('lacute',))
g(font, "public.kern2.lcommaaccent", ('lcommaaccent',))
g(font, "public.kern2.less", ('less', 'lessequal'))
g(font, "public.kern2.logicalnot", ('logicalnot',))
g(font, "public.kern2.lozenge", ('lozenge',))
g(font, "public.kern2.lslash", ('lslash',))
g(font, "public.kern2.macron", ('macron',))
g(font, "public.kern2.minus", ('minus',))
g(font, "public.kern2.multiply", ('multiply',))
g(font, "public.kern2.n", ('eng', 'm', 'n', 'nacute', 'ncaron', 'ncommaaccent', 'ntilde', 'p', 'r', 'racute'))
g(font, "public.kern2.nine", ('nine',))
g(font, "public.kern2.nine_numr", ('nine.numr',))
g(font, "public.kern2.nine_sinf", ('nine.sinf',))
g(font, "public.kern2.nine_sups", ('nine.sups',))
g(font, "public.kern2.notequal", ('notequal',))
g(font, "public.kern2.numbersign", ('numbersign',))
g(font, "public.kern2.o", ('c', 'cacute', 'ccaron', 'ccedilla', 'ccircumflex', 'cdotaccent', 'cent', 'd', 'dcaron', 'dcroat', 'e', 'eacute', 'ebreve', 'ecaron', 'ecircumflex', 'edieresis', 'edotaccent', 'egrave', 'emacron', 'eogonek', 'eth', 'o', 'oacute', 'obreve', 'ocircumflex', 'odieresis', 'oe', 'ograve', 'ohungarumlaut', 'omacron', 'omicron', 'omicrontonos', 'oslash', 'oslashacute', 'otilde', 'phi', 'q', 'sigma'))
g(font, "public.kern2.ogonek", ('ogonek',))
g(font, "public.kern2.one", ('one',))
g(font, "public.kern2.one_sinf", ('one.sinf',))
g(font, "public.kern2.onehalf", ('onehalf',))
g(font, "public.kern2.onequarter", ('onequarter',))
g(font, "public.kern2.ord", ('ordfeminine', 'ordmasculine'))
g(font, "public.kern2.paragraph", ('paragraph',))
g(font, "public.kern2.parenleft", ('parenleft',))
g(font, "public.kern2.parenright", ('parenright',))
g(font, "public.kern2.partialdiff", ('partialdiff',))
g(font, "public.kern2.percent", ('percent', 'perthousand'))
g(font, "public.kern2.period", ('ellipsis', 'period'))
g(font, "public.kern2.periodcentered", ('periodcentered',))
g(font, "public.kern2.pi", ('pi',))
g(font, "public.kern2.plus", ('plus', 'plusminus'))
g(font, "public.kern2.product", ('product',))
g(font, "public.kern2.question", ('question',))
g(font, "public.kern2.questiondown", ('questiondown',))
g(font, "public.kern2.quoteleft", ('quotedblleft', 'quoteleft'))
g(font, "public.kern2.quoteright", ('quotedblright', 'quoteright'))
g(font, "public.kern2.quotesingle", ('minute', 'quotedbl', 'quotesingle', 'second'))
g(font, "public.kern2.radical", ('radical',))
g(font, "public.kern2.registered", ('copyright', 'registered'))
g(font, "public.kern2.s", ('s', 'sacute', 'scaron', 'scedilla', 'scircumflex', 'scommaaccent'))
g(font, "public.kern2.schwa", ('schwa',))
g(font, "public.kern2.section", ('section',))
g(font, "public.kern2.semicolon", ('semicolon',))
g(font, "public.kern2.seven", ('seven',))
g(font, "public.kern2.seven_numr", ('seven.numr',))
g(font, "public.kern2.seven_sinf", ('seven.sinf',))
g(font, "public.kern2.seven_sups", ('seven.sups',))
g(font, "public.kern2.six", ('six',))
g(font, "public.kern2.six_numr", ('six.numr',))
g(font, "public.kern2.six_sinf", ('six.sinf',))
g(font, "public.kern2.six_sups", ('six.sups',))
g(font, "public.kern2.slash", ('slash',))
g(font, "public.kern2.space", ('space',))
g(font, "public.kern2.sterling", ('sterling',))
g(font, "public.kern2.summation", ('summation',))
g(font, "public.kern2.t", ('t', 'tbar', 'tcaron', 'tcedilla', 'tcommaaccent'))
g(font, "public.kern2.tecyrillic", ('hardsigncyrillic', 'tecyrillic'))
g(font, "public.kern2.three", ('three',))
g(font, "public.kern2.three_numr", ('three.numr',))
g(font, "public.kern2.three_sinf", ('three.sinf',))
g(font, "public.kern2.three_sups", ('three.sups',))
g(font, "public.kern2.threequarters", ('threequarters',))
g(font, "public.kern2.trademark", ('trademark',))
g(font, "public.kern2.two", ('two',))
g(font, "public.kern2.two_numr", ('two.numr',))
g(font, "public.kern2.two_sinf", ('two.sinf',))
g(font, "public.kern2.two_sups", ('two.sups',))
g(font, "public.kern2.u", ('u', 'uacute', 'ubreve', 'ucircumflex', 'udieresis', 'ugrave', 'uhungarumlaut', 'umacron', 'uogonek', 'uring', 'utilde'))
g(font, "public.kern2.ucyrillic", ('ucyrillic', 'ushortcyrillic'))
g(font, "public.kern2.underscore", ('underscore',))
g(font, "public.kern2.ustraightstrokecyrillic", ('ustraightstrokecyrillic',))
g(font, "public.kern2.v", ('nu', 'v', 'w', 'wacute', 'wcircumflex', 'wdieresis', 'wgrave'))
g(font, "public.kern2.vecyrillic", ('dzhecyrillic', 'emcyrillic', 'encyrillic', 'ercyrillic', 'gecyrillic', 'gheupturncyrillic', 'gjecyrillic', 'iicyrillic', 'iishortcyrillic', 'iucyrillic', 'kacyrillic', 'kadescendercyrillic', 'kjecyrillic', 'njecyrillic', 'pecyrillic', 'shacyrillic', 'shchacyrillic', 'tsecyrillic', 'vecyrillic', 'yericyrillic'))
g(font, "public.kern2.x", ('x',))
g(font, "public.kern2.y", ('y', 'yacute', 'ycircumflex', 'ydieresis', 'ygrave'))
g(font, "public.kern2.yen", ('yen',))
g(font, "public.kern2.yicyrillic", ('yicyrillic',))
g(font, "public.kern2.z", ('z', 'zacute', 'zcaron', 'zdotaccent'))
g(font, "public.kern2.zecyrillic", ('zecyrillic',))
g(font, "public.kern2.zero", ('zero',))
g(font, "public.kern2.zero_numr", ('zero.numr',))
g(font, "public.kern2.zero_salt_slash", ('zero.salt_slash',))
g(font, "public.kern2.zero_sinf", ('zero.sinf',))
g(font, "public.kern2.zero_sups", ('zero.sups',))
g(font, "public.kern2.zhecyrillic", ('hadescendercyrillic', 'khacyrillic', 'zhecyrillic', 'zhedescendercyrillic'))
g(font, "seven", ('TC1.seven_numr', 'TC2.seven_numr'))
g(font, "six", ('TC1.six_numr', 'TC2.six_numr'))
g(font, "three", ('TC1.three_numr', 'TC2.three_numr'))
g(font, "two", ('TC1.two_numr', 'TC2.two_numr'))
g(font, "zero", ('TC1.zero_numr', 'TC2.zero_numr'))

font.save()
font.close()
