#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#
#   P A G E B O T  N A N O
#
#   Copyright (c) 2020+ Buro Petr van Blokland + Claudia Mens
#   www.pagebot.io
#   Licensed under MIT conditions
#
#   Supporting DrawBot, www.drawbot.com
# -----------------------------------------------------------------------------
#
#   ThemeSpecimens.py
#
#   This ThemeColors.py shows samples of all standard theme colors,
#   with their closest spot color, CMYK, RGB, CSS hex-color and CSS name.
#
from random import shuffle
from pagebotnano_030.constants import (A4, LEFT, RIGHT, SPORTS, BIRDS, TOOLS,
    CITIES, FRUITS, COFFEES)
from pagebotnano_030.document import Document
from pagebotnano_030.elements import Rect, Text, Stacked
from pagebotnano_030.toolbox.color import Color
from pagebotnano_030.babelstring import BabelString

S = 4 # Scaling for Instagram
W, H = 1000*S, 1000*S
FONT = 'Georgia'
GUTTER_Y = 10*S
GUTTER_X = 40*S
PAD = 50*S

labelSize=15*S
labelColor = Color(0.8)
labelFontName = 'Upgrade-Medium'

SETS = (
    # Choose other fonts that exist on your computer here.
    (SPORTS, 'Sports', CITIES, 'Cities', 'Upgrade-Medium', 'Upgrade-MediumItalic', True),
    (BIRDS, 'Birds', FRUITS, 'Fruits', 'Upgrade-UltraBlack', 'Upgrade-UltraBlackItalic', True),
    (TOOLS, 'Tools', COFFEES, 'Coffees', 'Upgrade-Bold', 'Upgrade-BoldItalic', True),
)

for words1, title1, words2, title2, fontName1, fontName2, capsOnly in SETS:
    doc = Document(w=W, h=H)

    words1 = list(words1)
    words2 = list(words2)
    shuffle(words1)
    shuffle(words2)

    page = doc.newPage()
    page.padding = PAD

    cw = (page.pw-GUTTER_X)/2

    e = Stacked([title1] + words1, font=fontName1, x=page.pl, y=page.pt, 
        w=cw, h=page.ph, gh=GUTTER_Y, capsOnly=capsOnly, fill=0.9)
    page.addElement(e)

    e = Stacked([title2] + words2, font=fontName2, x=page.pl+cw+GUTTER_X, y=page.pt, 
        w=cw, h=page.ph, gh=GUTTER_Y, capsOnly=capsOnly, fill=0.9)
    page.addElement(e)


    footNoteStyle = dict(font=labelFontName, tracking=0.5, 
        fontSize=labelSize, fill=labelColor, align=LEFT)
    bs = BabelString('TYPETR '+fontName1, footNoteStyle)
    e = Text(bs, x=page.pl, y=page.pb/2, w=page.pw)
    page.addElement(e)

    footNoteStyle = dict(font=labelFontName, tracking=0.5, 
        fontSize=labelSize, fill=labelColor, align=LEFT)
    bs = BabelString('TYPETR '+fontName1, footNoteStyle)
    e = Text(bs, x=page.pl, y=page.pb/2, w=page.pw)
    page.addElement(e)

    footNoteStyle['align'] = RIGHT
    bs = BabelString('Generated by PageBotNano', footNoteStyle)
    e = Text(bs, x=page.pl+page.pw, y=page.pb/2, w=page.pw)
    page.addElement(e)

    doc.export('_export/Stacked-%s-%s.jpg' % (title1, title2), multipage=True) # Instagram 

print('Done 030')

